-- AlterTable
ALTER TABLE "public"."Curator" ALTER COLUMN "roleId" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "guildId" SET DATA TYPE VARCHAR(255);

-- AlterTable
ALTER TABLE "public"."Project" ALTER COLUMN "messageId" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "channelId" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "branchId" SET DATA TYPE VARCHAR(255);
